### ISSUE TITLE
Feature: Surrealdb connector 

### ISSUE THREAD

**Issue by nickchomey** [conduitio-labs/conduit-connector-elasticsearch#72]
### Feature description

I'm not sure if conduit has heard of Surrealdb, but it is a new and very promising "multi-model" database that covers relational, nosql, graph, vector, full text search, and more. It has received a lot of funding and attention, and should continue to grow. https://surrealdb.com/

I wonder if Conduit would consider creating or collaborating on a connector for it? I just mentioned the possibility in an existing issue for adding cdc to surreal, where theyve been discussing rolling their own - which makes no sense at all when something fantastic like Conduit exists.

Perhaps you could let them know if you have interest in collaborating on this? 

https://github.com/orgs/surrealdb/discussions/3

**Comment by lovromazgon** [comment]
For anyone who finds this issue in the future: https://github.com/ConduitIO/conduit/issues/1594.
